blueprint:
  name: zaluzie_lines
  description: A blueprint to control sunblinds, including stopping and opening them a little bit.
  domain: automation
  input:
    switch_up:
      name: Sunblind Up Switch
      description: The switch to control the up motion of the sunblind.
      selector:
        entity:
    switch_down:
      name: Sunblind Down Switch
      description: The switch to control the down motion of the sunblind.
      selector:
        entity:
    sunblind_power_sensor_down:
      name: Sunblind Power Sensor
      description: The sensor that monitors the power consumption of the sunblind.
      selector:
        entity:

mode: single
max_exceeded: silent

trigger: []
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: !input switch_up
  - service: switch.turn_on
    target:
      entity_id: !input switch_down
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: !input sunblind_power_sensor_down
        below: 3
        for:
          seconds: 1
    continue_on_timeout: false
  - service: switch.turn_off
    target:
      entity_id: !input switch_down
  - service: switch.turn_on
    target:
      entity_id: !input switch_up
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - service: switch.turn_off
    target:
      entity_id: !input switch_up
